version: '3.1'

services:
    database:
        mem_limit: 2048m
        image: mariadb:10.6.4-focal
        restart: unless-stopped
        ports:
            - 3306:3306
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
        volumes:
            - db:/var/lib/mysql
        networks:
            - wordpress-network
    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - 8081:80
        env_file: .env
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        networks:
            - wordpress-network

    wordpress:
        container_name: testing
        depends_on:
            - database
        image: wordpress:latest
        restart: unless-stopped
        ports: 
            - 8080:80
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
            WORDPRESS_DB_USER: '${MYSQL_USER}'
            WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
        volumes:
            - ./:/var/www/html
        networks:
            - wordpress-network
    jenkins:
        user: root  # Ensures Jenkins has necessary permissions
        privileged: true # Allows access to Docker
        image: jenkins/jenkins:lts
        container_name: jenkins
        restart: unless-stopped
        ports:
            - 8082:8080
        volumes:
            - jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - wordpress-network

volumes:
    db:
    jenkins-data:

networks:
    wordpress-network:
        driver: bridge